packages:
  - "examples/*"
  - "docs"
  - "packages/*"

catalog:
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  eslint: 9.39.1
  eslint-config-next: 16.1.1
  typescript: 5.9.3
  "@types/node": 22.19.3
  "@types/react": 19.2.3
  "@types/react-dom": 19.2.3

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
