packages:
  - "examples/*"
  - "docs"
  - "packages/*"

catalog:
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  eslint: 9.39.1
  eslint-config-next: 16.1.1
  typescript: 5.9.3
  "@types/node": 22.19.3
  "@types/react": 19.2.3
  "@types/react-dom": 19.2.3
  rollup: 4.54.0
  "@rollup/plugin-node-resolve": 16.0.3
  "@rollup/plugin-typescript": 12.3.0
  glob: 13.0.0
  rollup-plugin-preserve-directives: 0.4.0

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
